name: Publish release

on:
  push:
    tags:
      - "v[0-9]+"
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  release:
    name: Build distribution
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/p/portone-server-sdk
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: yezz123/setup-uv@v4
      - name: Install git-filter-repo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git-filter-repo
          version: "1.0"
      - name: Sync dependencies
        run: uv sync
      - name: Set github username
        run: |
          git config --global user.name runner
          git config --global user.email "runner@github.com"
          git config --global init.defaultBranch main
      - name: Generate sources
        run: |
          uv run scripts/gen-env.py
          uv run scripts/patch.py apply
      - name: Build distribution
        run: uvx --from build pyproject-build --installer uv
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v2.1.1
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes ""